INSERT INTO series VALUES (1,"LOTR", 1, 1);
INSERT INTO series VALUES (2, "A Song of Ice and Fire", 2, 2);
INSERT INTO books VALUES (1, "LOTR:The Fellowship of the Ring", 1954, 1);
INSERT INTO books VALUES (2, "LOTR: The Two Towers", 1954, 1);
INSERT INTO books VALUES (3, "LOTR: The Return of the King", 1955, 1);
INSERT INTO books VALUES (4, "A Song of Ice and Fire: A Game of Thrones: ", 1996, 2);
INSERT INTO books VALUES (5, "A Song of Ice and Fire: A Clash of Kings: ", 1998, 2);
INSERT INTO books VALUES (6, "A Song of Ice and Fire: A Feast of Crows: ", 2005, 2);
INSERT INTO characters VALUES (1, "Alfredo", "Smooth and Creamy", "human", 1);
INSERT INTO characters VALUES (2, "Antipasta", "I come first", "zorgellian", 1);
INSERT INTO characters VALUES (3, "Penne", "Never Quite Cooked", "human", 1);
INSERT INTO characters VALUES (4, "Linguini", "Thinner and Thinner", "spicellio", 1);
INSERT INTO characters VALUES (5, "Meatball", "Who Doesn't Love it?", "human", 2);
INSERT INTO characters VALUES (6, "Pepperoni", "I'm good with more than just pizza", "human", 1);
INSERT INTO characters VALUES (7, "Limoncello", "TANG!", "Sourvilleian", 2);
INSERT INTO characters VALUES (8, "Tomato", "Just hard enough", "human", 1);
INSERT INTO subgenres VALUES (1, "Dark Fantasy");
INSERT INTO subgenres VALUES (2, "Tasty Fantasy");
INSERT INTO authors VALUES (1, "J.R.R. Tolkien");
INSERT INTO authors VALUES (2, "Geroge R. R. Martin");
INSERT INTO character_books VALUES (1, 1, 1);
INSERT INTO character_books VALUES (2, 2, 1);
INSERT INTO character_books VALUES (3, 3, 1);
INSERT INTO character_books VALUES (4, 4, 1);
INSERT INTO character_books VALUES (5, 5, 1);
INSERT INTO character_books VALUES (6, 6, 1);
INSERT INTO character_books VALUES (7, 7, 1);
INSERT INTO character_books VALUES (8, 8, 1);
INSERT INTO character_books VALUES (9, 1, 2);
INSERT INTO character_books VALUES (10, 2, 2);
INSERT INTO character_books VALUES (11, 3, 2);
INSERT INTO character_books VALUES (12, 4, 2);
INSERT INTO character_books VALUES (13, 5, 2);
INSERT INTO character_books VALUES (14, 6, 2);
INSERT INTO character_books VALUES (15, 7, 2);
INSERT INTO character_books VALUES (16, 8, 2);
